### ISSUE TITLE
Testing trained model with Hvite

### ISSUE THREAD

**Issue by ersigcha23** [nassosoassos/spanish_voxforge_htk_asr#1]
Is there any way to test the resulting model with the HVite tool?

For some reason Hdecode doesn't work in my computer

Thanks

**Comment by nassosoassos** [comment]
Hi there,

apologies for the delayed reply. Which operating system are you working on? I could send you the binary probably.

best,
nassos

**Comment by ersigcha23** [comment]
Hi 

Thanks for answering

I'm working on OS X 10.11 El Capitan and when I run the HDecode part I'm getting multiple errors (Segmentation Faults and others). I'm trying to develop an online recognition service but since I can't use HDecode I'm stuck with this part

Thanks for helping

**Comment by nassosoassos** [comment]
Try this binary: 
http://cvsp.cs.ntua.gr/~nassos/HDecode
Works on my laptop :)
I assume you already have accepted the HTK license agreement. 

best,
nassos

**Comment by ersigcha23** [comment]
It worked!

Thanks I appreciate it. I spend a week trying to fix this problem.

By the way I'm using HTK for research purposes.

I would like to know if there was a special way to compile Decode on OS X?

**Comment by nassosoassos** [comment]
Yes, there was, I had to use:
CC = /Developer/usr/bin/gcc-4.0

But I remember doing that a few years back, it was not El Capitan then. But
it has worked ever since :)
